# Generated by Django 3.0.8 on 2020-10-27 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kanban table name', max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'kanban_style',
                'verbose_name_plural': 'kanban_styles',
                'db_table': 'kanban_styles',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='activity name', max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kanban table name', max_length=100)),
                ('kanban_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.KanbanStyle')),
            ],
            options={
                'verbose_name': 'kanban',
                'verbose_name_plural': 'kanbans',
                'db_table': 'kanbans',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='activity name', max_length=100)),
                ('Activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanban.Kanban')),
                ('tags', models.ManyToManyField(blank=True, to='kanban.Tag')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'db_table': 'activities',
            },
        ),
    ]
