# Generated by Django 3.0.8 on 2020-10-27 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='Activity',
            new_name='kanban',
        ),
    ]
